# Generated by Django 5.1.3 on 2024-11-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cantidad_actual', models.PositiveIntegerField()),
                ('cantidad_minima', models.PositiveSmallIntegerField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('historial', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
