# Generated by Django 5.1.1 on 2024-11-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha_actualizacion',
            field=models.DateField(),
        ),
    ]
